version: '3.1'
services:
  postgres:
    image: postgres:9.6
    restart: always
    container_name: MediaToyDB
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: ybenlafk
      POSTGRES_DB: mydb
    ports:
      - 5432:5432